### ISSUE TITLE
Container errors?

### ISSUE THREAD

**Issue by wunderlife** [kidkych/smplifyx-and-openpose-containers#1] opened 2022-09-27 09:20 UTC
When I execute ./run_smplifyx.sh, I got following errors:

src/bvh.cpp: In function ‘at::Tensor bvh_forward(at::Tensor, int)’:
src/bvh.cpp:25:39: warning: ‘at::DeprecatedTypeProperties& at::Tensor::type() const’ is deprecated: Tensor.type() is deprecated. Instead use Tensor.options(), which in many cases (e.g. in a constructor) is a drop-in replacement. If you were using data from type(), that is now available from Tensor itself, so instead of tensor.type().scalar_type(), use tensor.scalar_type() instead and instead of tensor.type().backend() use tensor.device(). [-Wdeprecated-declarations]
 #define CHECK_CUDA(x) AT_CHECK(x.type().is_cuda(), #x " must be a CUDA tensor")
                                       ^
src/bvh.cpp:27:24: note: in expansion of macro ‘CHECK_CUDA’
 #define CHECK_INPUT(x) CHECK_CUDA(x); CHECK_CONTIGUOUS(x)
                        ^~~~~~~~~~
src/bvh.cpp:30:5: note: in expansion of macro ‘CHECK_INPUT’
     CHECK_INPUT(triangles);
     ^
In file included from /usr/local/lib/python3.6/dist-packages/torch/include/ATen/Tensor.h:3:0,
                 from /usr/local/lib/python3.6/dist-packages/torch/include/ATen/Context.h:4,
                 from /usr/local/lib/python3.6/dist-packages/torch/include/ATen/ATen.h:9,
                 from /usr/local/lib/python3.6/dist-packages/torch/include/torch/csrc/api/include/torch/types.h:3,
                 from /usr/local/lib/python3.6/dist-packages/torch/include/torch/csrc/api/include/torch/data/dataloader_options.h:4,
                 from /usr/local/lib/python3.6/dist-packages/torch/include/torch/csrc/api/include/torch/data/dataloader/base.h:3,
                 from /usr/local/lib/python3.6/dist-packages/torch/include/torch/csrc/api/include/torch/data/dataloader/stateful.h:3,
                 from /usr/local/lib/python3.6/dist-packages/torch/include/torch/csrc/api/include/torch/data/dataloader.h:3,
                 from /usr/local/lib/python3.6/dist-packages/torch/include/torch/csrc/api/include/torch/data.h:3,
                 from /usr/local/lib/python3.6/dist-packages/torch/include/torch/csrc/api/include/torch/all.h:8,
                 from /usr/local/lib/python3.6/dist-packages/torch/include/torch/extension.h:4,
                 from src/bvh.cpp:18:
/usr/local/lib/python3.6/dist-packages/torch/include/ATen/core/TensorBody.h:194:30: note: declared here
   DeprecatedTypeProperties & type() const {
                              ^~~~
src/bvh.cpp:25:23: error: ‘AT_CHECK’ was not declared in this scope
 #define CHECK_CUDA(x) AT_CHECK(x.type().is_cuda(), #x " must be a CUDA tensor")
                       ^
src/bvh.cpp:25:23: note: in definition of macro ‘CHECK_CUDA’
 #define CHECK_CUDA(x) AT_CHECK(x.type().is_cuda(), #x " must be a CUDA tensor")
                       ^~~~~~~~
src/bvh.cpp:30:5: note: in expansion of macro ‘CHECK_INPUT’
     CHECK_INPUT(triangles);
     ^
src/bvh.cpp:25:23: note: suggested alternative: ‘DCHECK’
 #define CHECK_CUDA(x) AT_CHECK(x.type().is_cuda(), #x " must be a CUDA tensor")
                       ^
src/bvh.cpp:25:23: note: in definition of macro ‘CHECK_CUDA’
 #define CHECK_CUDA(x) AT_CHECK(x.type().is_cuda(), #x " must be a CUDA tensor")
                       ^~~~~~~~
src/bvh.cpp:30:5: note: in expansion of macro ‘CHECK_INPUT’
     CHECK_INPUT(triangles);
     ^
/usr/local/lib/python3.6/dist-packages/setuptools/command/install.py:37: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  setuptools.SetuptoolsDeprecationWarning,
/usr/local/lib/python3.6/dist-packages/setuptools/command/easy_install.py:159: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
  EasyInstallDeprecationWarning,
/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py:119: PkgResourcesDeprecationWarning: .5 is an invalid version and will not be supported in a future release
  PkgResourcesDeprecationWarning,
/usr/local/lib/python3.6/dist-packages/torch/utils/cpp_extension.py:381: UserWarning: Attempted to use ninja as the BuildExtension backend but we could not find ninja.. Falling back to using the slow distutils backend.
  warnings.warn(msg.format('we could not find ninja.'))
/usr/local/lib/python3.6/dist-packages/torch/utils/cpp_extension.py:782: UserWarning: The detected CUDA version (10.0) has a minor version mismatch with the version that was used to compile PyTorch (10.2). Most likely this shouldn't be a problem.
  warnings.warn(CUDA_MISMATCH_WARN.format(cuda_str_version, torch.version.cuda))
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
The command '/bin/sh -c git clone https://github.com/vchoutas/torch-mesh-isect && cd torch-mesh-isect &&     pip3 install -r requirements.txt && python3 setup.py install' returned a non-zero code: 1

xhost:  unable to open display ""
Unable to find image 'smplifyx_container:latest' locally
docker: Error response from daemon: pull access denied for smplifyx_container, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
See 'docker run --help'.

How do I solve this?

**Comment by kidkych** [comment] 2022-10-07 17:26
Looks like an error with the `torch-mesh-isect` package that is used to compute interpenetration. I no longer update this repo, but it seems like [this pull-request](https://github.com/vchoutas/torch-mesh-isect/pull/31) for the `torch-mesh-isect` package solves the problem you're having. Until the pull-request is merged into vchoutas's repo you can change the repo url on line 24 of the dockerfile at `smplify-x/Dockerfile` from `https://github.com/vchoutas/torch-mesh-isect` to `https://github.com/prajwalsingh/torch-mesh-isect`.

Let me know how it goes

**Comment by wunderlife** [comment] 2022-10-12 09:09
Still it does not work.

where can i find the image?

creating build/temp.linux-x86_64-3.6
creating build/temp.linux-x86_64-3.6/src
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/local/lib/python3.6/dist-packages/torch/include -I/usr/local/lib/python3.6/dist-packages/torch/include/torch/csrc/api/include -I/usr/local/lib/python3.6/dist-packages/torch/include/TH -I/usr/local/lib/python3.6/dist-packages/torch/include/THC -Iinclude -I/home/repos/cuda-samples/Common -I/usr/local/lib/python3.6/dist-packages/torch/include -I/usr/local/lib/python3.6/dist-packages/torch/include/torch/csrc/api/include -I/usr/local/lib/python3.6/dist-packages/torch/include/TH -I/usr/local/lib/python3.6/dist-packages/torch/include/THC -I/usr/local/cuda/include -I/usr/include/python3.6m -c src/bvh.cpp -o build/temp.linux-x86_64-3.6/src/bvh.o -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE="_gcc" -DPYBIND11_STDLIB="_libstdcpp" -DPYBIND11_BUILD_ABI="_cxxabi1011" -DTORCH_EXTENSION_NAME=bvh_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14
In file included from /usr/local/lib/python3.6/dist-packages/torch/include/c10/core/DeviceType.h:8:0,
                 from /usr/local/lib/python3.6/dist-packages/torch/include/c10/core/Device.h:3,
                 from /usr/local/lib/python3.6/dist-packages/torch/include/c10/core/Allocator.h:6,
                 from /usr/local/lib/python3.6/dist-packages/torch/include/ATen/ATen.h:7,
                 from /usr/local/lib/python3.6/dist-packages/torch/include/torch/csrc/api/include/torch/types.h:3,
                 from /usr/local/lib/python3.6/dist-packages/torch/include/torch/csrc/api/include/torch/data/dataloader_options.h:4,
                 from /usr/local/lib/python3.6/dist-packages/torch/include/torch/csrc/api/include/torch/data/dataloader/base.h:3,
                 from /usr/local/lib/python3.6/dist-packages/torch/include/torch/csrc/api/include/torch/data/dataloader/stateful.h:3,
                 from /usr/local/lib/python3.6/dist-packages/torch/include/torch/csrc/api/include/torch/data/dataloader.h:3,
                 from /usr/local/lib/python3.6/dist-packages/torch/include/torch/csrc/api/include/torch/data.h:3,
                 from /usr/local/lib/python3.6/dist-packages/torch/include/torch/csrc/api/include/torch/all.h:8,
                 from /usr/local/lib/python3.6/dist-packages/torch/include/torch/extension.h:4,
                 from src/bvh.cpp:18:
src/bvh.cpp: In function ‘at::Tensor bvh_forward(at::Tensor, int)’:
src/bvh.cpp:25:42: warning: ‘at::DeprecatedTypeProperties& at::Tensor::type() const’ is deprecated: Tensor.type() is deprecated. Instead use Tensor.options(), which in many cases (e.g. in a constructor) is a drop-in replacement. If you were using data from type(), that is now available from Tensor itself, so instead of tensor.type().scalar_type(), use tensor.scalar_type() instead and instead of tensor.type().backend() use tensor.device(). [-Wdeprecated-declarations]
 #define CHECK_CUDA(x) TORCH_CHECK(x.type().is_cuda(), #x " must be a CUDA tensor")
                                          ^
/usr/local/lib/python3.6/dist-packages/torch/include/c10/macros/Macros.h:197:64: note: in definition of macro ‘C10_UNLIKELY’
 #define C10_UNLIKELY(expr) (__builtin_expect(static_cast<bool>(expr), 0))
                                                                ^~~~
/usr/local/lib/python3.6/dist-packages/torch/include/c10/util/Exception.h:441:7: note: in expansion of macro ‘C10_UNLIKELY_OR_CONST’
   if (C10_UNLIKELY_OR_CONST(!(cond))) {            \
       ^~~~~~~~~~~~~~~~~~~~~
src/bvh.cpp:25:23: note: in expansion of macro ‘TORCH_CHECK’
 #define CHECK_CUDA(x) TORCH_CHECK(x.type().is_cuda(), #x " must be a CUDA tensor")
                       ^~~~~~~~~~~
src/bvh.cpp:27:24: note: in expansion of macro ‘CHECK_CUDA’
 #define CHECK_INPUT(x) CHECK_CUDA(x); CHECK_CONTIGUOUS(x)
                        ^~~~~~~~~~
src/bvh.cpp:30:5: note: in expansion of macro ‘CHECK_INPUT’
     CHECK_INPUT(triangles);
     ^
In file included from /usr/local/lib/python3.6/dist-packages/torch/include/ATen/Tensor.h:3:0,
                 from /usr/local/lib/python3.6/dist-packages/torch/include/ATen/Context.h:4,
                 from /usr/local/lib/python3.6/dist-packages/torch/include/ATen/ATen.h:9,
                 from /usr/local/lib/python3.6/dist-packages/torch/include/torch/csrc/api/include/torch/types.h:3,
                 from /usr/local/lib/python3.6/dist-packages/torch/include/torch/csrc/api/include/torch/data/dataloader_options.h:4,
                 from /usr/local/lib/python3.6/dist-packages/torch/include/torch/csrc/api/include/torch/data/dataloader/base.h:3,
                 from /usr/local/lib/python3.6/dist-packages/torch/include/torch/csrc/api/include/torch/data/dataloader/stateful.h:3,
                 from /usr/local/lib/python3.6/dist-packages/torch/include/torch/csrc/api/include/torch/data/dataloader.h:3,
                 from /usr/local/lib/python3.6/dist-packages/torch/include/torch/csrc/api/include/torch/data.h:3,
                 from /usr/local/lib/python3.6/dist-packages/torch/include/torch/csrc/api/include/torch/all.h:8,
                 from /usr/local/lib/python3.6/dist-packages/torch/include/torch/extension.h:4,
                 from src/bvh.cpp:18:
/usr/local/lib/python3.6/dist-packages/torch/include/ATen/core/TensorBody.h:194:30: note: declared here
   DeprecatedTypeProperties & type() const {
                              ^~~~
/usr/local/lib/python3.6/dist-packages/setuptools/command/install.py:37: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  setuptools.SetuptoolsDeprecationWarning,
/usr/local/lib/python3.6/dist-packages/setuptools/command/easy_install.py:159: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
  EasyInstallDeprecationWarning,
/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py:119: PkgResourcesDeprecationWarning: .5 is an invalid version and will not be supported in a future release
  PkgResourcesDeprecationWarning,
/usr/local/lib/python3.6/dist-packages/torch/utils/cpp_extension.py:381: UserWarning: Attempted to use ninja as the BuildExtension backend but we could not find ninja.. Falling back to using the slow distutils backend.
  warnings.warn(msg.format('we could not find ninja.'))
/usr/local/lib/python3.6/dist-packages/torch/utils/cpp_extension.py:782: UserWarning: The detected CUDA version (10.0) has a minor version mismatch with the version that was used to compile PyTorch (10.2). Most likely this shouldn't be a problem.
  warnings.warn(CUDA_MISMATCH_WARN.format(cuda_str_version, torch.version.cuda))
Traceback (most recent call last):
  File "setup.py", line 97, in <module>
    cmdclass={'build_ext': BuildExtension})
  File "/usr/local/lib/python3.6/dist-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/usr/local/lib/python3.6/dist-packages/setuptools/command/install.py", line 74, in run
    self.do_egg_install()
  File "/usr/local/lib/python3.6/dist-packages/setuptools/command/install.py", line 116, in do_egg_install
    self.run_command('bdist_egg')
  File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/usr/local/lib/python3.6/dist-packages/setuptools/command/bdist_egg.py", line 164, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "/usr/local/lib/python3.6/dist-packages/setuptools/command/bdist_egg.py", line 150, in call_command
    self.run_command(cmdname)
  File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/usr/local/lib/python3.6/dist-packages/setuptools/command/install_lib.py", line 11, in run
    self.build()
  File "/usr/lib/python3.6/distutils/command/install_lib.py", line 109, in build
    self.run_command('build_ext')
  File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/usr/local/lib/python3.6/dist-packages/setuptools/command/build_ext.py", line 79, in run
    _build_ext.run(self)
  File "/usr/lib/python3.6/distutils/command/build_ext.py", line 339, in run
    self.build_extensions()
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/cpp_extension.py", line 735, in build_extensions
    build_ext.build_extensions(self)
  File "/usr/lib/python3.6/distutils/command/build_ext.py", line 448, in build_extensions
    self._build_extensions_serial()
  File "/usr/lib/python3.6/distutils/command/build_ext.py", line 473, in _build_extensions_serial
    self.build_extension(ext)
  File "/usr/local/lib/python3.6/dist-packages/setuptools/command/build_ext.py", line 202, in build_extension
    _build_ext.build_extension(self, ext)
  File "/usr/lib/python3.6/distutils/command/build_ext.py", line 533, in build_extension
    depends=ext.depends)
  File "/usr/lib/python3.6/distutils/ccompiler.py", line 574, in compile
    self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/cpp_extension.py", line 483, in unix_wrap_single_compile
    cflags = unix_cuda_flags(cflags)
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/cpp_extension.py", line 450, in unix_cuda_flags
    cflags + _get_cuda_arch_flags(cflags))
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/cpp_extension.py", line 1606, in _get_cuda_arch_flags
    arch_list[-1] += '+PTX'
IndexError: list index out of range
The command '/bin/sh -c git clone https://github.com/prajwalsingh/torch-mesh-isect && cd torch-mesh-isect &&     pip3 install -r requirements.txt && python3 setup.py install' returned a non-zero code: 1
[sudo] password for dcrc: 
sudo: xhost: command not found
Unable to find image 'smplifyx_container:latest' locally
docker: Error response from daemon: pull access denied for smplifyx_container, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
See 'docker run --help'.

**Comment by kidkych** [comment] 2022-10-15 14:55
When you execute ./run_smplifyx.sh the image will be built, I haven't pushed it to the docker repos so it needs to be built locally.

Unfortunately I'm not sure what the issue is. I won't have time to fix this for a while as I'm currently in the process of writing my thesis; I suggest you look at other potential containers for smplifyx or create your own

**Closed as not planned** 2022-10-15 14:55 UTC
